document.domain="naver.com";var nhn;if(!nhn||!nhn.ac){if(!nhn)
nhn=new Object();if(!nhn.ac)
nhn.ac=new Object();}
nhn.ac.Utility={B:"block",I:"inline",N:"none",UD:"undefined",Class:function(){var constructor=function(){if(this.__init)this.__init.apply(this,arguments);}
if(arguments[0])constructor.prototype=arguments[0];return constructor;},extend:function(source,append){var obj=source;for(var x in append)obj[x]=append[x];return obj;},eventRegister:function(oEl,sEvent,pFunc){try{oEl=this.$(oEl);if(oEl.addEventListener){if(sEvent=="mousewheel")sEvent="DOMMouseScroll";oEl.addEventListener(sEvent,pFunc,false);}else if(oEl.attachEvent){oEl.attachEvent('on'+sEvent,pFunc);}}catch(e){}},$:function(id){var ret=[];for(var i=0;i<arguments.length;i++){if(typeof arguments[i]=='string'){ret[ret.length]=document.getElementById(arguments[i]);}else{ret[ret.length]=arguments[i];}}
return ret[1]?ret:ret[0];},$A:function(collection){var ret=[];for(var i=0;i<collection.length;i++)ret[ret.length]=collection[i];return ret;},getCookie:function(n){var cn=n+"=",x=0;while(x<=document.cookie.length){var y=(x+cn.length);if(document.cookie.substring(x,y)==cn){if((end=document.cookie.indexOf(";",y))==-1)
end=document.cookie.length;return unescape(document.cookie.substring(y,end));}
x=document.cookie.indexOf(" ",x)+1;if(x==0)break;}
return"";},setCookie:function(n,v,e,d){if(e==0)
document.cookie=n+"="+escape(v)+"; PATH=/; DOMAIN="+d+";";else{var tda=new Date();tda.setDate(tda.getDate()+e);document.cookie=n+"="+escape(v)+"; PATH=/; EXPIRES="+tda.toGMTString()+"; DOMAIN="+d+";";}},tagEncode:function(s){s=s.replace(/\'/g,"&#39;");s=s.replace(/\"/g,"&quot;");return s;},tagDecode:function(s){s=s.replace(/&#0?39;/g,"'");s=s.replace(/&quot;/g,"\"");s=s.replace(/&amp;/g,"&");s=s.replace(/&lt;/g,"<");s=s.replace(/&gt;/g,">");return s;},escape:function(s){s=s.replace(/ /g,"%20");s=s.replace(/\+/g,"%2B");s=s.replace(/&/g,"%26");s=s.replace(/=/g,"%3D");return s;},substring:function(s,start,len){var i,l=0,d="";for(i=start;i<s.length&&l<len;i++){if(s.charCodeAt(i)>127)
l+=2;else
l++;d+=s.substr(i,1);}
return d;},makeHighPre:function(s,t){var d="";var s1=s.replace(/ /g,"");var t1=t.replace(/ /g,"");t1=t1.toLowerCase();if(t1==s1.substring(0,t1.length)){d="<strong>";for(var i=0,j=0;j<t1.length;i++){if(s.substring(i,i+1)!=" ")
j++;d+=s.substring(i,i+1);}
d+="</strong>"+s.substring(i,s.length);}
return d;},makeHighSuf:function(s,t){var d="";var s1=s.replace(/ /g,"");var t1=t.replace(/ /g,"");t1=t1.toLowerCase();if(t1==s1.substring(s1.length-t1.length)){for(var i=0,j=0;j<s1.length-t1.length;i++){if(s.substring(i,i+1)!=" ")
j++;d+=s.substring(i,i+1);}
d+="<strong>";for(var k=i,l=0;l<t1.length;k++){if(s.substring(k,k+1)!=" ")
l++;d+=s.substring(k,k+1);}
d+="</strong>";}
return d;},highlight:function(s,d,eq,is_suf){var ret="";if(!is_suf){ret=this.makeHighPre(s,d);if(ret=="")
ret=this.makeHighPre(s,eq);}else{ret=this.makeHighSuf(s,d);if(ret=="")
ret=this.makeHighSuf(s,eq);}
if(ret=="")
return s;else
return ret;},getNavigator:function(){var info=new Object;var ver=-1;var u=navigator.userAgent;var v=navigator.vendor||"";var f=function(s,h){return((h||"").indexOf(s)>-1)};info.opera=(typeof window.opera!="undefined")||f("Opera",u);info.ie=!info.opera&&f("MSIE",u);info.chrome=f("Chrome",u);info.safari=!info.chrome&&f("Apple",v);info.mozilla=f("Gecko",u)&&!info.safari&&!info.chrome;info.firefox=f("Firefox",u);info.camino=f("Camino",v);info.netscape=f("Netscape",u);info.omniweb=f("OmniWeb",u);info.icab=f("iCab",v);info.konqueror=f("KDE",v);try{if(info.ie){ver=u.match(/(?:MSIE) ([0-9.]+)/)[1];}else if(info.firefox||info.opera||info.omniweb){ver=u.match(/(?:Firefox|Opera|OmniWeb)\/([0-9.]+)/)[1];}else if(info.mozilla){ver=u.match(/rv:([0-9.]+)/)[1];}else if(info.safari){ver=parseFloat(u.match(/Safari\/([0-9.]+)/)[1]);if(ver==100){ver=1.1;}else{ver=[1.0,1.2,-1,1.3,2.0,3.0][Math.floor(ver/100)];}}else if(info.icab){ver=u.match(/iCab[ \/]([0-9.]+)/)[1];}else if(info.chrome){ver=u.match(/Chrome[ \/]([0-9.]+)/)[1];}
info.version=parseFloat(ver);if(isNaN(info.version))info.version=-1;}catch(e){info.version=-1;}
return info;},trimSpace:function(ke,me){if(me==0){ke=ke.replace(/ /g,"");}else if(me==1){ke=ke.replace(/^ +/g,"");ke=ke.replace(/ +$/g," ");}else if(me==2){ke=ke.replace(/^ +/g," ");ke=ke.replace(/ +$/g,"");}
ke=ke.replace(/ +/g," ");return ke;},eCancel:function(e){e.returnValue=false;if(e&&e.preventDefault)
e.preventDefault();},getCkAcUse:function(cn_ac){var s=this.getCookie(cn_ac);return typeof(s)==nhn.ac.Utility.UD?"":s;},addClickEvent:function(obj,func){var oldClick=obj.onclick;if(typeof obj.onclick!="function"){obj.onclick=func;}else{obj.onclick=function(){oldClick();func();}}},cutStr:function(str,myCut,hanSize,engUpperSize,engLowSize,others){var cnt=0;var cutPos=str.length;for(var i=0;i<str.length;i++){var code=str.charAt(i).charCodeAt(0);if((code>=44032&&code<=552013)||(code>=12593&&code<=12643)){cnt+=hanSize;}else if(code>=65&&code<=90){if(code==73&&code==74){cnt+=engLowSize;}else{cnt+=engUpperSize;}}else if(code>=97&&code<=122){cnt+=engLowSize;}else{cnt+=others;}
if(Math.floor(cnt)>myCut){cutPos=i;break;}}
return(cutPos<str.length?str.substring(0,cutPos)+"...":str);},callCutStr:function(str,myCut){return this.cutStr(str,myCut,2,2,1,1);},getReq:function(_req){if(_req&&_req.readyState!=0){_req.abort();}
try{_req=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{_req=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){_req=false;}}
if(!_req&&typeof XMLHttpRequest!=this.UD)
_req=new XMLHttpRequest();return _req;}}
nhn.ac.Utility.extend(Function.prototype,{bind:function(obj){var f=this,a=nhn.ac.Utility.$A(arguments);a.shift();return function(){return f.apply(obj,a);}},bindForEvent:function(obj){var f=this,a=nhn.ac.Utility.$A(arguments);return function(e){a[0]=e||window.event;return f.apply(obj,a);}}});nhn.ac.Display=nhn.ac.Utility.Class({Fn:"",inputName:"",Lt:{},Lb:{},F:{},FWindow:{},Da:{},Db:{},Ar:{},qsSet:{},bak:"",old:"",dnc:0,h_on:0,a_now:0,a_on:0,arr_on:0,frm_on:0,is_suf:0,more_suf:0,ft:0,fl:0,ft_b:0,fl_b:0,ws:0,tw:0,cn_ac:"nsr_acl",ck_dn:"naver.com",ck_ed:30,acuse:1,mpimg:"http://sstatic.naver.com/search/images11",arrImgOn:"/btn_atcmp_up_on.gif",arrImgOff:"/btn_atcmp_up_off.gif",arrImgOn2:"/btn_atcmp_down_on.gif",arrImgOff2:"/btn_atcmp_down_off.gif",__init:function(fn){this.options=nhn.ac.Utility.extend({docType:"quirks",formName:"search",inputName:"query",layerName:"nautocomplete",ifrmSrc:"./acNew.html",max_ql:60,scroll:false,htmlList:"<li id='{id}' class='aton'><a href='#' id='{aid}'>{title}</a><input type='hidden' id='{oid}' value='{ovalue}' /></li>",ft_ie:19,fl_ie:367,ft_ff:13,fl_ff:365,ft_op:13,fl_op:365,ft_b_ie:38,fl_b_ie:118,ft_b_ff:32,fl_b_ff:116,ft_b_op:38,fl_b_op:118,tw_ie:270,tw_ff:270,tw_op:270,ws_ie:960,ws_ff:980,ws_op:980,debug:false},arguments[0]||{});var o=this.options;this.Fn=o.formName;this.inputName=o.inputName;this.oNavi=nhn.ac.Utility.getNavigator();if(this.oNavi.ie){this.ft=o.ft_ie;this.fl=o.fl_ie;this.ft_b=o.ft_b_ie;this.fl_b=o.fl_b_ie;this.ws=o.ws_ie;this.tw=o.tw_ie;if(o.docType=="XHTML"&&this.oNavi.version=="5.5"){this.fl=o.fl_ie-5;this.tw=o.tw_ie-6;}}else if(this.oNavi.firefox||this.oNavi.safari||this.oNavi.chrome){this.ft=o.ft_ff;this.fl=o.fl_ff;this.ft_b=o.ft_b_ff;this.fl_b=o.fl_b_ff;this.ws=o.ws_ff;this.tw=o.tw_ff;}else if(this.oNavi.opera){this.ft=o.ft_op;this.fl=o.fl_op;this.ft_b=o.ft_b_op;this.fl_b=o.fl_b_op;this.ws=o.ws_op;this.tw=o.tw_op;}
this.acuse=nhn.ac.Utility.getCkAcUse(this.cn_ac);if(this.acuse=="")
this.acuse=1;nhn.ac.Utility.setCookie(this.cn_ac,this.acuse,this.ck_ed,this.ck_dn);var div1=document.createElement("div");var div2=document.createElement("div");div1.id=this.Fn+"mp_toplayer";div1.style.display="none";div2.id=this.Fn+"mp_bodylayer";div2.style.display="none";var iframe1=document.createElement("iframe");iframe1.id=this.Fn+"ifr_query";iframe1.name=this.Fn+"ifr_query";iframe1.src=o.ifrmSrc;iframe1.frameBorder=0;iframe1.marginwidth="0";iframe1.marginheight="0";iframe1.topmargin="0";iframe1.scrolling="no";iframe1.style.zIndex="100";div2.appendChild(iframe1);nhn.ac.Utility.$(o.layerName).appendChild(div1);nhn.ac.Utility.$(o.layerName).appendChild(div2);nhn.ac.Utility.eventRegister(this.Fn+"ifr_query","load",this.mpInit.bind(this));},mpInit:function(){this.Lt=nhn.ac.Utility.$(this.Fn+"mp_toplayer");this.Lb=nhn.ac.Utility.$(this.Fn+"mp_bodylayer");this.F=nhn.ac.Utility.$(this.Fn+"ifr_query");IFRMNAME=this.F;this.FWindow=this.F.contentWindow;this.Da=this.FWindow.document.getElementById("ac_body");this.Db=this.FWindow.document.getElementById("hp_body");this.acList=this.FWindow.document.getElementById("ac_list");this.spanSufMore=this.FWindow.document.getElementById("spanSufMore");nhn.ac.Utility.eventRegister(this.Da,"mouseover",this.setMouseOn.bind(this,2));nhn.ac.Utility.eventRegister(this.Da,"mouseout",this.setMouseOff.bind(this,2));nhn.ac.Utility.eventRegister(this.Db,"mouseover",this.setMouseOn.bind(this,2));nhn.ac.Utility.eventRegister(this.Db,"mouseout",this.setMouseOff.bind(this,2));this.F.style.width=this.tw+"px";this.mpPrintTop();this.mpPrintBody(0);},setMouseOn:function(f){if(f==1)
this.arr_on=1;else if(f==2)
this.frm_on=1;},setMouseOff:function(f){if(f==1)
this.arr_on=0;else if(f==2)
this.frm_on=0;},setFSize:function(o){this.F.width=o.offsetWidth+"px";this.F.height=o.offsetHeight+"px";},getTopEvent:function(){nhn.ac.Utility.eventRegister(this.Fn+"arrspan","click",function(){if(this.acuse==0){this.hpLayer();}else{this.acUsing();}}.bind(this));nhn.ac.Utility.eventRegister(this.Fn+"arrspan","mouseover",function(){this.arr_on=1;}.bind(this));nhn.ac.Utility.eventRegister(this.Fn+"arrspan","mouseout",function(){this.arr_on=0;}.bind(this));},getTop:function(){var n=0;var a=this.ft;var b=n+this.fl;var btn="";if(this.acuse==1)btn=this.arrImgOn2;else btn=this.arrImgOff2;var s="";s+="<div id=mp_top_div style=\"position:absolute;top:"+a+"px;left:"+b+"px;z-index:100\">";s+="<span id='"+this.Fn+"arrspan' onfocus='this.blur();' style='cursor:pointer;'>";s+="<img id='"+this.Fn+"arr' src='"+this.mpimg+btn+"' border='0' style='cursor:pointer'>";s+="</span>";s+="</div>";return s;},mpPrintTop:function(){this.Lt.innerHTML=this.getTop();this.getTopEvent();this.Lt.style.display=nhn.ac.Utility.B;this.Ar=nhn.ac.Utility.$(this.Fn+"arr");},mpPrintBody:function(flag){var n=0;var a=this.ft_b;var b=n+this.fl_b;this.Lb.style.position='absolute';this.Lb.style.top=a+"px";this.Lb.style.left=b+"px";this.Lb.style.zIndex=100;switch(flag){case 0:this.Db.style.display=nhn.ac.Utility.N;this.Lb.style.display=nhn.ac.Utility.N;break;case 1:this.Db.style.display=nhn.ac.Utility.B;break;case 2:this.Db.style.display=nhn.ac.Utility.I;break;}},getAcMessage:function(f){var msg="?? ???? ??? ???? ????";if(f=="using"){}else if(f=="noresult"){msg="?? ??? ???? ???? ????";}
this.setSufMore("");return"<div><p class='msg'>"+msg+"</p></div>";},acUsing:function(){this.dnc=1;if(this.Da.style.display==nhn.ac.Utility.B){this.acHide();return;}
var o=this.acList;o.innerHTML=this.getAcMessage("using");o.style.display=nhn.ac.Utility.B;this.setArrImg(true,this.arrImgOn,this.arrImgOff);this.Da.style.display=nhn.ac.Utility.B;this.Lb.style.display=nhn.ac.Utility.B;this.setFSize(this.Da);},hpLayer:function(){if(this.Db.style.display==nhn.ac.Utility.N)
this.hpShow();else
this.hpHide();},hpShow:function(){this.acHide();this.h_on=1;this.Lt.innerHTML=this.getTop();this.getTopEvent();this.setArrImg(false,this.arrImgOff);this.Db.style.display=nhn.ac.Utility.B;this.Lb.style.display=nhn.ac.Utility.B;this.setFSize(this.Db);},hpHide:function(){if(this.Db.style.display==nhn.ac.Utility.N)
return;this.h_on=0;this.Lt.innerHTML=this.getTop();this.getTopEvent();this.setArrImg(false,this.arrImgOff2);this.Db.style.display=nhn.ac.Utility.N;this.Lb.style.display=nhn.ac.Utility.N;},acHide:function(){if(this.Da.style.display==nhn.ac.Utility.N)
return;this.setArrImg(true,this.arrImgOn2,this.arrImgOff2);this.Da.style.display=nhn.ac.Utility.N;this.Lb.style.display=nhn.ac.Utility.N;this.a_on=this.a_now=this.is_suf=0;},setArrImg:function(isSet,onImg,offImg){this.Ar=nhn.ac.Utility.$(this.Fn+"arr");if(isSet){if(this.acuse==1)
this.Ar.src=this.mpimg+onImg;else
this.Ar.serc=this.mpimg+offImg;}else{this.Ar.src=this.mpimg+onImg;}},printAc:function(obj){this.qsSet=obj;this.setSufMore("");var o=this.acList;if(!this.qsSet.qs_ac_len&&!this.qsSet.qs_opp_len&&this.ipc==1)
o.innerHTML=this.getAcMessage("noresult");else{if(this.options.scroll){o.innerHTML="<div id=\"acScroll\" class=\"words\">"+this.getAcList().replace(/{oppclass}/,"other")+"</div>";}else{o.innerHTML=this.getAcList().replace(/{oppclass}/,"other");}}
o.style.display=nhn.ac.Utility.B;setTimeout(this.setAhl.bind(this),10);if(this.qsSet.qs_m==2)
this.is_suf=1;else if(!this.more_suf&&this.qsSet.qs_m!=2)
this.is_suf=0;this.more_suf=0;if(this.qsSet.qs_ac_len||this.qsSet.qs_opp_len){this.a_on=1;}else{this.a_on=0;if(this.ipc==1)this.qsSet.qs_ac_len=1;}
if(this.qsSet.qs_ac_len>0){this.setArrImg(true,this.arrImgOn,this.arrImgOff);}else{this.setArrImg(true,this.arrImgOn2,this.arrImgOff2);}
this.Da.style.display=nhn.ac.Utility.B;this.Lb.style.display=nhn.ac.Utility.B;if(this.qsSet.qs_ac_len||this.qsSet.qs_opp_len){this.setFSize(this.Da);}else{this.setFSize({"offsetWidth":this.Da.offsetWidth,"offsetHeight":0});this.Da.style.display=nhn.ac.Utility.N;}},addList:function(obj){var ret=this.options.htmlList
for(var i=0;i<obj.length;i++){ret=ret.replace(new RegExp(obj[i].exp),obj[i].value)}
return ret;},getAcList:function(){var d="",ds="",i=0,l=0,s="";if(this.qsSet.qs_ac_list[0]!=""||this.qsSet.qs_opp_list[0]!=""){s+="<ul>";for(i=0;i<this.qsSet.qs_ac_len;i++){ds=d=this.qsSet.qs_ac_list[i];ds=nhn.ac.Utility.callCutStr(d,this.options.max_ql);ds=nhn.ac.Utility.highlight(ds,this.qsSet.qs_q,this.qsSet.qs_errata,this.is_suf);s+=this.addList([{"exp":"{id}","value":"actd"+(i+1)},{"exp":"{title}","value":ds},{"exp":"{aid}","value":"aca"+(i+1)},{"exp":"{oid}","value":"acq"+(i+1)},{"exp":"{ovalue}","value":d}]);}
if(this.qsSet.qs_ac_len&&this.qsSet.qs_opp_len){s+="</ul><ul class=\"{oppclass}\">";}
for(j=0;j<this.qsSet.qs_opp_len;j++){ds=d=this.qsSet.qs_opp_list[j];ds=nhn.ac.Utility.callCutStr(d,this.options.max_ql);ds=nhn.ac.Utility.highlight(ds,this.qsSet.qs_q,this.qsSet.qs_errata,!this.is_suf);var nt=(i+j+1);s+=this.addList([{"exp":"{id}","value":"actd"+nt},{"exp":"{title}","value":ds},{"exp":"{aid}","value":"aca"+nt},{"exp":"{oid}","value":"acq"+nt},{"exp":"{ovalue}","value":d}]);}
s+="</ul>";if(this.qsSet.qs_opp_list.length>0){var ment="";if(!this.is_suf){ment="??? ";}else{ment="??? ";}
this.setSufMore("<a href='#' onclick='return false;' id='acListSufMore' style='cursor:pointer;' class='run_view'>"+ment+" ???</a> ");}}
return s;},setAcpos:function(v){this.a_now=v;setTimeout(this.setAhl.bind(this),10);},setAhl:function(){if(!this.a_on)
return;var o1,o2;for(i=0;i<this.qsSet.qs_ac_len+this.qsSet.qs_opp_len;i++){o1=this.FWindow.document.getElementById('actd'+(i+1));if((i+1)==this.a_now)
o1.className='naverpgn_on';else
o1.className='';}},setSufMore:function(val){this.spanSufMore.innerHTML=val;}});nhn.ac.Controller=nhn.ac.Utility.Class({oForm:{},oFrame:{},Ip:{},wiInt:100,wiTimer:null,cc:{},_req:false,qsSet:{qs_ac_list:"",qs_ac_id:"",qs_q:"",qs_m:0,qs_ac_len:0,qs_opp_list:"",qs_opp_len:0,qs_errata:"",qs_err_ac_list:"",qs_err_opp_list:"",qs_max:10,qs_opp_max:10},__init:function(){this.oDisplay=new nhn.ac.Display(arguments[0]);this.oForm=document.forms[this.oDisplay.Fn];this.oFrame=nhn.ac.Utility.$(this.oDisplay.Fn+"ifr_query");this.oFrameWindow=nhn.ac.Utility.$(this.oDisplay.Fn+"ifr_query").contentWindow;this.Ip=this.oForm[this.oDisplay.inputName];this.oDisplay.old=this.Ip.value;nhn.ac.Utility.eventRegister(this.oDisplay.Fn+"ifr_query","load",this.initController.bind(this));},initController:function(){if(this.oDisplay.acuse==1)
this.Ip.setAttribute("autocomplete","off");else if(this.oDisplay.acuse==0)
this.Ip.setAttribute("autocomplete","on");nhn.ac.Utility.eventRegister(this.Ip,"click",this.reqIpc.bind(this));nhn.ac.Utility.eventRegister(this.Ip,"blur",this.disP.bind(this));nhn.ac.Utility.addClickEvent(document,this.disP.bind(this));nhn.ac.Utility.eventRegister(this.oFrame.contentWindow.document.getElementById("hpBodyShowAc"),"click",this.showAc.bind(this,1));nhn.ac.Utility.eventRegister(this.oFrame.contentWindow.document.getElementById("acBodyShowAc"),"click",this.showAc.bind(this,0));this._observer();},$iframe:function(el){return this.oDisplay.FWindow.document.getElementById(el);},_observer:function(){return setTimeout(this.wi.bind(this),this.wiInt);},wi:function(){if(this.oDisplay.acuse==0)
return;if(this.oDisplay.h_on){this._observer();return;}
var now=this.Ip.value;if(now==""&&now!=this.oDisplay.old)
this.oDisplay.acHide();if(now!=""&&now!=this.oDisplay.old&&top.keystatus!=1){var o=null,me=0;o=this.getCc(me);if(o&&(o[1][0]!=""||o[3][0]!=""))
this.acShow(o[0],o[1],o[2],me,o[3],o[4],o[5],o[6]);else
this.reqAC(me);}
this.oDisplay.old=now;this.wiTimer=this._observer();},disP:function(){if(this.oDisplay.dnc){this.oDisplay.dnc=0;return;}
if(this.oDisplay.arr_on){return;}
if(this.oDisplay.frm_on){return;}
this.oDisplay.acHide();this.oDisplay.hpHide();setTimeout(this.wi.bind(this),this.wiInt);},showAc:function(v){this.oDisplay.acuse=v;nhn.ac.Utility.setCookie(this.oDisplay.cn_ac,this.oDisplay.acuse,this.oDisplay.ck_ed,this.oDisplay.ck_dn);if(this.oDisplay.acuse==1){this.Ip.setAttribute("autocomplete","off");this.oDisplay.hpHide();setTimeout(this.wi.bind(this),this.wiInt);this.reqIpc();}else if(this.oDisplay.acuse==0){this.Ip.setAttribute("autocomplete","on");this.oDisplay.acHide();}
this.oDisplay.mpPrintTop();this.oDisplay.dnc=0;},acShow:function(aq,al,ai,am,ol,eq,el,eol){this.initScrollBase();if(!this.oDisplay.more_suf&&aq&&aq!=""&&aq!=nhn.ac.Utility.trimSpace(this.Ip.value,am))
return;var i,j=0,row_h=0;var al_t=new Array;var ol_t=new Array;var el_t=new Array;var eol_t=new Array;this.qsSet.exist_escape=false;for(i=0;i<al.length;i++){al_t[i]=al[i];}
for(i=0,j=0;i<ol.length;i++){if(aq.toLowerCase()!=ol[i]){ol_t[j++]=ol[i];}}
for(i=0,j=0;i<el.length;i++)
if(eq.toLowerCase()!=el[i])
el_t[j++]=el[i];for(i=0,j=0;i<eol.length;i++)
if(eq.toLowerCase()!=eol[i])
eol_t[j++]=eol[i];if(eq!=""&&al.length<this.qsSet.qs_max){if(aq.toLowerCase()!=eq.toLowerCase())
al_t[al.length]=eq;var len=al_t.length;for(i=0;i<this.qsSet.qs_max-len&&i<el_t.length;i++)
al_t[len+i]=el_t[i];}
if(eq!=""&&ol_t.length<this.qsSet.qs_opp_max){var len=ol_t.length;for(i=0;i<this.qsSet.qs_opp_max-len&&i<eol_t.length;i++)
ol_t[len+i]=eol_t[i];}
this.oDisplay.hpHide();setTimeout(this.wi.bind(this),this.wiInt);this.qsSet.qs_q=aq;this.qsSet.qs_errata=eq;this.qsSet.qs_m=am;this.qsSet.qs_ac_list=al_t;this.qsSet.qs_opp_list=ol_t;this.qsSet.qs_ac_id=ai;this.qsSet.qs_ac_len=this.qsSet.qs_ac_list.length;this.qsSet.qs_opp_len=(this.qsSet.qs_opp_list.length>3)?3:this.qsSet.qs_opp_list.length;this.oDisplay.printAc(this.qsSet);if(this.qsSet.qs_ac_len||this.qsSet.qs_opp_len||this.oDisplay.ipc==0){this.setAcListEvent();}
if(this.oDisplay.a_on){this.oDisplay.setAcpos(0);if(this.oDisplay.oNavi.ie||this.oDisplay.oNavi.opera||this.oDisplay.oNavi.safari||this.oDisplay.oNavi.chrome){this.Ip.onkeydown=this.ackhl.bindForEvent(this);}else if(this.oDisplay.oNavi.firefox){this.Ip.onkeypress=this.ackhl.bindForEvent(this);}}
this.qsSet.qs_ac_list=al;this.qsSet.qs_opp_list=ol;this.qsSet.qs_err_ac_list=el;this.qsSet.qs_err_opp_list=eol;},setAcListEvent:function(){var d="",ds="",i=0,l=0,s="";if(this.qsSet.qs_ac_list[0]!=""||this.qsSet.qs_opp_list[0]!=""){for(i=0;i<this.qsSet.qs_ac_len;i++){nhn.ac.Utility.eventRegister(this.$iframe("actd"+(i+1)),"click",this.clickAcList.bind(this,this.qsSet.qs_ac_list[i],(i+1)));}
for(j=0;j<this.qsSet.qs_opp_len;j++){var nt=(i+j+1);nhn.ac.Utility.eventRegister(this.$iframe("actd"+nt),"click",this.clickAcList.bind(this,this.qsSet.qs_opp_list[j],(i+j+1)));}
if(this.qsSet.qs_opp_list.length>0){nhn.ac.Utility.eventRegister(this.$iframe("acListSufMore"),"click",this.sufMore.bind(this));}}},clickAcList:function(value,nt){this.oDisplay.old=this.Ip.value=nhn.ac.Utility.tagEncode(value);clearTimeout(this.wiTimer);try{if(parent.cr_log==1){var url="http://cr.naver.com/rd?a=sug.click&f="+g_sv+"&r="+nt+"&m=1&u="+escape("http://search.naver.com/search.naver?where=nexearch&query="+nhn.ac.Utility.escape(escape(value))+"&sm=top_sug");window.location=url;}else{this.submitForm();}}catch(e){if(this.oDisplay.options.debug)alert(e);}
return false;},submitForm:function(){try{this.oForm["sm"].value="top_sug";}catch(e){if(this.oDisplay.options.debug)alert(e);}
this.oForm.submit();},scrollBase:{row:4,s:1,e:4,top:0,dispTop:0},initScrollBase:function(){this.scrollBase={row:4,s:1,e:4,top:0,dispTop:0};},ackhl:function(event){var e=event||window.event;var o1,o2;if(e.keyCode==39){this.reqAc2(1);}
if(e.keyCode==13){if(this.oDisplay.a_now>0){this.submitForm();nhn.ac.Utility.eCancel(e);}}
var acScroll=this.$iframe("acScroll");var base=this.scrollBase;if(e.keyCode==40||(e.keyCode==9&&!e.shiftKey)){if(this.oDisplay.h_on)
return;if(!this.oDisplay.a_on){this.reqAc2(1);return;}
if(this.oDisplay.a_now<this.qsSet.qs_ac_len+this.qsSet.qs_opp_len){if(this.oDisplay.a_now==0)this.oDisplay.bak=this.Ip.value;this.oDisplay.a_now++;o1=this.$iframe('actd'+this.oDisplay.a_now);o2=this.$iframe('acq'+this.oDisplay.a_now);this.oDisplay.old=this.Ip.value=nhn.ac.Utility.tagDecode(o2.value);if(!this.scrollBase.dispTop)this.scrollBase.dispTop=this.$iframe('actd1').offsetTop;if(this.oDisplay.options.scroll){if(this.oDisplay.a_now>base.e){if(this.oDisplay.a_now<=this.qsSet.qs_ac_list.length){acScroll.scrollTop=this.$iframe("actd"+(this.oDisplay.a_now-base.row+1)).offsetTop-base.dispTop;}else{acScroll.scrollTop=this.$iframe("actd"+(this.oDisplay.a_now-base.row+1)).offsetTop-base.dispTop+10;}
base.s++;base.e++;}else if(this.oDisplay.a_now==base.e){if(this.qsSet.qs_opp_list.length>0&&this.oDisplay.a_now>this.qsSet.qs_ac_list.length){acScroll.scrollTop=this.$iframe("actd"+(this.oDisplay.a_now-base.row+1)).offsetTop-base.dispTop+10;}}}
this.Ip.focus();this.oDisplay.setAhl();nhn.ac.Utility.eCancel(e);}}
if(this.oDisplay.a_on&&(e.keyCode==38||(e.keyCode==9&&e.shiftKey))){if(!this.oDisplay.a_on)
return;if(this.oDisplay.a_now<=1){this.oDisplay.acHide();this.oDisplay.old=this.Ip.value;nhn.ac.Utility.eCancel(e);}else{this.oDisplay.a_now--;o1=this.$iframe('actd'+this.oDisplay.a_now);o2=this.$iframe('acq'+this.oDisplay.a_now);this.oDisplay.old=this.Ip.value=nhn.ac.Utility.tagDecode(o2.value);if(this.oDisplay.options.scroll){if(this.oDisplay.a_now<base.s){acScroll.scrollTop=o1.offsetTop-this.scrollBase.dispTop;base.s--;base.e--;}else if(this.oDisplay.a_now==base.s){if(this.qsSet.qs_opp_list.length>0&&base.e>this.qsSet.qs_ac_list.length){acScroll.scrollTop=o1.offsetTop-this.scrollBase.dispTop;}}}
this.Ip.focus();this.oDisplay.setAhl();nhn.ac.Utility.eCancel(e);}}},getCc:function(me){var ke=nhn.ac.Utility.trimSpace(this.Ip.value,me)+me;return typeof(this.cc[ke])==nhn.ac.Utility.UD?null:this.cc[ke];},setCc:function(aq,al,ai,me,ol,eq,el,eo){this.cc[aq+me]=new Array(aq,al,ai,ol,eq,el,eo);},reqAc2:function(me){if(this.Ip.value==""||this.oDisplay.acuse==0)
return;if(this.oDisplay.a_on&&this.oDisplay.dnc&&me==0){this.oDisplay.acHide();return;}
var o=this.getCc(me);if(o&&(o[1][0]!=""||o[3][0]!=""))
this.acShow(o[0],o[1],o[2],me,o[3],o[4],o[5],o[6]);else
this.reqAC(me);},reqIpc:function(){this.oDisplay.dnc=1;this.oDisplay.frm_on=0;this.oDisplay.ipc=1;this.reqAc2(0);this.oDisplay.ipc=0;},includeScript:function(t,d,s,c){if(this._req)
document.getElementsByTagName('head')[0].removeChild(this._req);var script=document.createElement('script');script.src=s;script.type=t;script.defer=d;script.charset=c;document.getElementsByTagName('head')[0].appendChild(script);return script;},reqAC:function(me){oCurrentAC=this;var navigator=this.oDisplay.oNavi;var ke=nhn.ac.Utility.escape(escape(nhn.ac.Utility.trimSpace(this.Ip.value,me)));if(ke==""){this.oDisplay.acHide();return;}
try{var sv;if(g_sv=='music'||g_sv=='dic'){sv="/autocompl_"+g_sv+"?r=1&m="+me+"&q="+ke;}else if(navigator.firefox&&navigator.version=="1.5"){sv="http://naver.com/autocompl?r=1&m="+me+"&q="+ke;}else{sv="/autocompl?r=1&m="+me+"&q="+ke;}
this.request({method:"js",url:sv});}catch(e){if(this.oDisplay.options.debug)alert(e);}},_req:null,request:function(json){var charset=json.charset||"euc-kr";if(json.method=="Ajax"){this._req=nhn.ac.Utility.getReq();if(this._req){this._req.open("GET",json.url,true);this._req.onreadystatechange=json.callback.bind(this,this._req);}
try{this._req.send(null);}catch(e){if(this.oDisplay.options.debug)alert(e);return 0;}}else if(json.method=="js"){try{this._req=this.includeScript('text/javascript',true,json.url,charset);}catch(e){if(this.oDisplay.options.debug)alert(e);return 0;}}},sufMore:function(){this.oDisplay.is_suf=!this.oDisplay.is_suf;this.oDisplay.more_suf=1;this.oDisplay.frm_on=0;this.acShow(this.qsSet.qs_q,this.qsSet.qs_opp_list,this.qsSet.qs_ac_id,this.qsSet.qs_m,this.qsSet.qs_ac_list,this.qsSet.qs_errata,this.qsSet.qs_err_opp_list,this.qsSet.qs_err_ac_list);this.Ip.focus();return false;}});var oCurrentAC;var qs_ac_id="";set_cc=function(qs_q,qs_ac_list,qs_ac_id,qs_m,qs_opp_list,qs_errata,qs_err_ac_list,qs_err_opp_list){oCurrentAC.setCc(qs_q,qs_ac_list,qs_ac_id,qs_m,qs_opp_list,qs_errata,qs_err_ac_list,qs_err_opp_list);}
ac_show=function(qs_q,qs_ac_list,qs_ac_id,qs_m,qs_opp_list,qs_errata,qs_err_ac_list,qs_err_opp_list){oCurrentAC.acShow(qs_q,qs_ac_list,qs_ac_id,qs_m,qs_opp_list,qs_errata,qs_err_ac_list,qs_err_opp_list);}