excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://stophobia.github.io
title: Stophobia
email: stophobia@gmail.com
author: stophobia
description: I am 
paginate: 10
google_analytics: UA-36770240-1
highlighter: rouge
