[production]
;phpSettings.display_startup_errors = 0
phpSettings.display_startup_errors = 1
;phpSettings.display_errors = 0
phpSettings.display_errors = 1
includePaths.library = APPLICATION_PATH "/../library"
bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"
appnamespace = "Application"
resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers"
resources.frontController.params.displayExceptions = 1
;resources.frontController.params.displayExceptions = 0

[staging : production]

[testing : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1

[development : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1
resources.frontController.params.displayExceptions = 1


[database_main]
adapter = pdo_mysql
params.host = localhost
params.dbname = KIDSLINK
params.username = dev4db
params.password = tlssksek
params.charset = utf8
params.profiler = 1

[database_slave]
adapter = pdo_mysql
params.host = localhost
params.dbname = KIDSLINK
params.username = dev4db
params.password = tlssksek
params.charset = utf8
params.profiler = 1

[log]
level=6
;DEBUG=7,INFO=6,NOTICE=5,WARN=4,ERR=3,CRIT=2,ALERT=1,EMERG=0
