<?php $clickheatConf = array (
  'logPath' => '/home/stophobia/public_html/indicator/logs/',
  'cachePath' => '/home/stophobia/public_html/indicator/cache/',
  'referers' => false,
  'groups' => false,
  'filesize' => 0,
  'adminLogin' => 'stophobia',
  'adminPass' => '7cbc08576ec2d6ac527b4654492521c8',
  'viewerLogin' => '',
  'viewerPass' => '',
  'memory' => 128,
  'step' => 5,
  'dot' => 19,
  'flush' => 40,
  'start' => 'm',
  'palette' => false,
  'heatmap' => true,
  'hideIframes' => false,
  'hideFlashes' => false,
  'yesterday' => false,
  'alpha' => 80,
  '__screenSizes' => 
  array (
    0 => 0,
    1 => 240,
    2 => 640,
    3 => 800,
    4 => 1024,
    5 => 1152,
    6 => 1280,
    7 => 1440,
    8 => 1600,
    9 => 1800,
  ),
  '__browsersList' => 
  array (
    'all' => '',
    'msie' => 'Internet Explorer',
    'firefox' => 'Firefox',
    'chrome' => 'Chrome',
    'safari' => 'Safari',
    'opera' => 'Opera',
    'unknown' => '',
  ),
  'version' => '1.11',
); ?>