tinyMCE.addI18n('en.advanced_dlg',{
about_title:"GR시리즈에 사용된 TinyMCE에 관하여...",
about_general:"소개",
about_help:"도움말",
about_license:"라이센스",
about_plugins:"플러그인들",
about_plugin:"플러그인",
about_author:"제작자",
about_version:"버젼",
about_loaded:"사용중인 플러그인들",
anchor_title:"Insert/edit anchor",
anchor_name:"Anchor name",
code_title:"HTML 태그로 게시물 직접 작성하기",
code_wordwrap:"단어 감싸기",
colorpicker_title:"색상선택",
colorpicker_picker_tab:"Picker",
colorpicker_picker_title:"색상 선택",
colorpicker_palette_tab:"팔레트",
colorpicker_palette_title:"팔레트 색상들",
colorpicker_named_tab:"Named",
colorpicker_named_title:"명명된 색상들",
colorpicker_color:"색깔:",
colorpicker_name:"이름:",
charmap_title:"Select custom character",
image_title:"이미지 삽입/수정",
image_src:"이미지 URL",
image_alt:"이미지 설명",
image_list:"이미지 목록",
image_border:"테두리",
image_dimensions:"Dimensions",
image_vspace:"수직 공간",
image_hspace:"수평 공간",
image_align:"정렬",
image_align_baseline:"기준선",
image_align_top:"상단",
image_align_middle:"중간",
image_align_bottom:"하단",
image_align_texttop:"글자상단",
image_align_textbottom:"글자하단",
image_align_left:"왼쪽",
image_align_right:"오른쪽",
link_title:"링크 입력/수정",
link_url:"링크 URL",
link_target:"대상",
link_target_same:"현재창에서 링크열기",
link_target_blank:"새 창에서 링크열기",
link_titlefield:"제목",
link_is_email:"입력하신 URL 이 메일주소로 보입니다. 자동으로 mailto: 를 붙일까요?",
link_is_external:"입력하신 URL이 외부로 향하는 링크로 보입니다. 자동으로 http:// 를 붙일까요?",
link_list:"Link list"
});