/**
 * Click IME for simple naver
 * @author gony
 * @version r1791
 */

var ClickIME={textbox:null,composing:false,offset:0,inputmode:0,lastChar:[-1,-1,-1],firstcons:{},finalcons:{},vowels:{},init:function(textboxID){var i,c,ch,offset=0,self=this;var func=function(e){self.lastChar=[-1,-1,-1];};this.textbox=document.getElementById(textboxID);function addEvent(sEvent,pFunc){var box=self.textbox;if(box.addEventListener){box.addEventListener(sEvent,pFunc,false);}else if(box.attachEvent){box.attachEvent("on"+sEvent,pFunc);}}
addEvent("keydown",func);addEvent("mousedown",func);var firstcons="\u3131\u3132\u3134\u3137\u3138\u3139\u3141\u3142\u3143\u3145\u3146\u3147\u3148\u3149\u314A\u314B\u314C\u314D\u314E";for(i=0;i<firstcons.length;i++){ch=firstcons.substring(i,i+1);this.firstcons[ch]=i;}
var comb_cons={"\u3131":{"\u3145":3},"\u3134":{"\u3148":5,"\u314E":6},"\u3139":{"\u3131":9,"\u3141":10,"\u3142":11,"\u3145":12,"\u314C":13,"\u314D":14,"\u314E":15},"\u3142":{"\u3145":18}};var not_finals="\u3138\u3143\u3149";for(i=12593;i<12623;i++){ch=String.fromCharCode(i);if(not_finals.indexOf(ch)>-1){offset--;continue;}
this.finalcons[ch]={$:i-12592+offset};for(c in(comb_cons[ch]||{})){this.finalcons[ch][c]=comb_cons[ch][c];}}
var comb_vowels={"\u3157":{"\u314F":9,"\u3150":10,"\u3163":11},"\u315C":{"\u3153":14,"\u3154":15,"\u3163":16},"\u3161":{"\u3163":19}};for(i=12623;i<12644;i++){ch=String.fromCharCode(i);this.vowels[ch]={$:i-12623};for(c in(comb_vowels[ch]||{})){this.vowels[ch][c]=comb_vowels[ch][c];}}},clear:function(){this.lastChar=[-1,-1,-1];this.textbox.value="";this.textbox.focus();},erase:function(){if(this.lastChar[0]==-1||this.lastChar[1]==-1){this._delChar(1);this.lastChar=[-1,-1,-1];return;}
if(this.lastChar[2]!=-1){var cons=this._getCons(this.lastChar[2]);if(cons.length>1){this.lastChar[2]=cons[1];}else{this.lastChar[2]=-1;}}else{this.lastChar[1]=-1;}
this._delChar(1);this._addChar(this._makeChar());},put:function(charcode){var ch=String(charcode);if(ch.charCodeAt(0)>128){return this._putUnicode(ch);}else{return this._putAnsi(ch);}},_putAnsi:function(sChar){this.composing=false;this.lastChar=[-1,-1,-1];this._addChar(sChar);},_putUnicode:function(sChar){var unit,init=false;switch(this._charMode(sChar)){case 1:if(this.lastChar[0]==-1||this.lastChar[1]==-1){this.lastChar=[this.firstcons[sChar],-1,-1];}else if(this.lastChar[2]!=-1){unit=this._getUnit(2);if(this.finalcons[unit]&&this.finalcons[unit][sChar]){this.lastChar[2]=this.finalcons[unit][sChar];this._delChar(1);}else{this.lastChar=[this.firstcons[sChar],-1,-1];}}else if(this.finalcons[sChar]){this.lastChar[2]=this.finalcons[sChar].$;this._delChar(1);}else if(this.firstcons[sChar]){this.lastChar=[this.firstcons[sChar],-1,-1];}else{this._delChar(1);}
this._addChar(this._makeChar());break;case 2:if(this.lastChar[2]!=-1){var cons=this._getCons(this.lastChar[2]);if(cons.length==1){this.lastChar[2]=0;}else{this.lastChar[2]=cons[1];}
this._delChar(1);this._addChar(this._makeChar());this.lastChar=[cons[0],this.vowels[sChar].$,-1];}else if(this.lastChar[1]!=-1){unit=this._getUnit(1);if(this.vowels[unit]&&this.vowels[unit][sChar]){this.lastChar[1]=this.vowels[unit][sChar];this._delChar(1);}else{init=true;this.lastChar=[-1,this.vowels[sChar].$,-1];}}else{if(this.lastChar[0]==-1){this.lastChar[1]=this.vowels[sChar].$;}else{this._delChar(1);this.lastChar[1]=this.vowels[sChar].$;}}
this._addChar(this._makeChar());break;}
if(init)this.lastChar=[-1,-1,-1];},_addChar:function(sChar){this.textbox.value+=sChar;this._focus();},_delChar:function(nCount){var sVal=this.textbox.value;this.textbox.value=sVal.substring(0,sVal.length-nCount);this._focus();},_makeChar:function(){if(this.lastChar[0]==-1){if(this.lastChar[1]!=-1)return String.fromCharCode(this.lastChar[1]+12623);return"";}
if(this.lastChar[1]==-1){var code=this.lastChar[0];if(code>8)code+=11;else if(code>5)code+=10;else if(code>2)code+=3;else if(code>1)code+=1;return String.fromCharCode(code+12593);}
var finalCon=Math.max(this.lastChar[2],0);return String.fromCharCode(44032+this.lastChar[0]*21*28+this.lastChar[1]*28+finalCon);},_charMode:function(sChar){var nCode=sChar.charCodeAt(0);if(nCode>12592&&nCode<12623){return 1;}else if(nCode>12622&&nCode<12644){return 2;}else{return 0;}},_getCons:function(nIndex){for(var c1 in this.finalcons){for(var c2 in this.finalcons[c1]){if(nIndex==this.finalcons[c1][c2]){if(c2=='$')return[this.firstcons[c1]];else return[this.firstcons[c2],this.finalcons[c1].$];}}}},_getUnit:function(idx){var names=["firstcons","vowels","finalcons"];var units=this[names[idx]];var val=this.lastChar[idx];if(val==-1)return"";for(var x in units){if((idx?units[x].$:units[x])==val)return x;}
return"";},_focus:function(){var sel,rng;this.textbox.focus();if(document.selection){sel=document.selection;rng=sel.createRange();rng.move("character",this.textbox.length);rng.select();}}}
