tinyMCE.addI18n('en.advanced',{
style_select:"스타일",
font_size:"글씨크기",
fontdefault:"글꼴",
block:"형태",
paragraph:"Paragraph",
div:"Div",
address:"Address",
pre:"Preformatted",
h1:"Heading 1",
h2:"Heading 2",
h3:"Heading 3",
h4:"Heading 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"Code",
samp:"Code sample",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"굵게 (Ctrl+B)",
italic_desc:"기울이기 (Ctrl+I)",
underline_desc:"밑줄 (Ctrl+U)",
striketrough_desc:"취소선",
justifyleft_desc:"Align left",
justifycenter_desc:"Align center",
justifyright_desc:"Align right",
justifyfull_desc:"Align full",
bullist_desc:"Unordered list",
numlist_desc:"Ordered list",
outdent_desc:"내어쓰기",
indent_desc:"들여쓰기",
undo_desc:"취소 (Ctrl+Z)",
redo_desc:"다시 복구 (Ctrl+Y)",
link_desc:"링크 삽입/수정",
unlink_desc:"Unlink",
image_desc:"이미지 삽입/수정",
cleanup_desc:"Cleanup messy code",
code_desc:"HTML 태그로 작성하기",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"수평선",
removeformat_desc:"Remove formatting",
custom1_desc:"Your custom description here",
forecolor_desc:"글자색 선택",
backcolor_desc:"글자배경색 선택",
charmap_desc:"Insert custom character",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Insert/edit anchor",
cut_desc:"잘라내기",
copy_desc:"복사하기",
paste_desc:"붙여넣기",
image_props_desc:"이미지 속성",
newdocument_desc:"새 문서",
help_desc:"도움말 (영문)",
blockquote_desc:"Blockquote",
clipboard_msg:"복사/잘라내기/붙여넣기는 불여우에서 사용이 불가능합니다.\r\n이 문제와 관련한 정보를 확인해 보시겠습니까?",
path:"경로",
newdocument:"모든 컨텐츠들를 정말로 깨끗히 지우시겠습니까?",
toolbar_focus:"도구버튼으로: Alt+Q, 에디터로: Alt-Z, 객체 경로로: Alt-X",
more_colors:"더 많은 색상..."
});