tinyMCE.addI18n('en.advanced',{
style_select:"스타일",
font_size:"글꼴 크기",
fontdefault:"글꼴 종류",
block:"형식",
paragraph:"단락",
div:"Div",
address:"주소",
pre:"미리 정의됨",
h1:"헤드 1",
h2:"헤드 2",
h3:"헤드 3",
h4:"헤드 4",
h5:"헤드 5",
h6:"헤드 6",
blockquote:"인용",
code:"Code",
samp:"Code sample",
dt:"용어 정의 (dt)",
dd:"정의 설명 (dd)",
bold_desc:"굵게 (Ctrl+B)",
italic_desc:"기울이기 (Ctrl+I)",
underline_desc:"밑줄 (Ctrl+U)",
striketrough_desc:"취소선",
justifyleft_desc:"왼쪽 정렬",
justifycenter_desc:"중간 정렬",
justifyright_desc:"오른쪽 정렬",
justifyfull_desc:"양쪽 정렬",
bullist_desc:"순서 없는 목록",
numlist_desc:"순서 있는 목록",
outdent_desc:"내어쓰기",
indent_desc:"들여쓰기",
undo_desc:"취소 (Ctrl+Z)",
redo_desc:"복구 (Ctrl+Y)",
link_desc:"링크 삽입/수정",
unlink_desc:"링크 취소",
image_desc:"그림 삽입/수정",
cleanup_desc:"메시코드 삭제",
code_desc:"HTML 직접 수정하기",
sub_desc:"아래 첨자",
sup_desc:"상단 첨자",
hr_desc:"수평 줄자 삽입",
removeformat_desc:"형식 제거",
custom1_desc: "이 곳에 나의 설명 입력",
forecolor_desc:"글자 색상 선택",
backcolor_desc:"배경 색상 선택",
charmap_desc:"커스텀 문자 삽입",
visualaid_desc:"가이드라인/숨기기 항목 전환",
anchor_desc:"앵커 삽입/수정",
cut_desc:"잘라내기",
copy_desc:"복사하기",
paste_desc:"붙여넣기",
image_props_desc:"그림 속성들",
newdocument_desc:"새 문서",
help_desc:"도움말",
blockquote_desc:"인용",
clipboard_msg:"복사/잘라내기/붙이기는 불여우 브라우저에서 지원되지 않습니다.\n이 문제에 관해 더 알아보시겠습니까?",
path:"경로",
newdocument:"작성하신 내용을 모두 잃게 됩니다. 계속 진행할까요?",
toolbar_focus:"도구 버튼으로 이동 - Alt+Q, 에디터로 이동 - Alt-Z, 항목 경로로 이동 - Alt-X",
more_colors:"더 많은 색상"
});